# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flytectl < Formula
  desc "FlyteCtl is a command line tool to interact with a Flyte cluster."
  homepage "https://docs.flyte.org/projects/flytectl"
  version "0.6.22"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/flyteorg/flytectl/releases/download/v0.6.22/flytectl_Darwin_arm64.tar.gz"
      sha256 "3bb769f3cfcaabf129afea3749e41a02681c4664b141721bd4c9a0004e9f7e7b"

      def install
        bin.install "flytectl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flyteorg/flytectl/releases/download/v0.6.22/flytectl_Darwin_x86_64.tar.gz"
      sha256 "b84547fdcecc09fe607072472749fa05c7c9b489e1a6d17a2f503d3891609cc5"

      def install
        bin.install "flytectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyteorg/flytectl/releases/download/v0.6.22/flytectl_Linux_arm64.tar.gz"
      sha256 "b8ed10bb422f990f783cc2f35eaf25a35284f2163e9b9c833d36b272de293a18"

      def install
        bin.install "flytectl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flyteorg/flytectl/releases/download/v0.6.22/flytectl_Linux_x86_64.tar.gz"
      sha256 "74abb27d7db1c43e82e2af0753f0da2791b7aaeb8844bb391087ff3fae8593ed"

      def install
        bin.install "flytectl"
      end
    end
  end
end
