# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flytectl < Formula
  desc "FlyteCtl is a command line tool to interact with a Flyte cluster."
  homepage "https://docs.flyte.org/projects/flytectl"
  version "0.6.30"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/flyteorg/flytectl/releases/download/v0.6.30/flytectl_Darwin_arm64.tar.gz"
      sha256 "aea02f481feb23675cf5844faa9a41005efd66aae3f054b616895f4f5df5e190"

      def install
        bin.install "flytectl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flyteorg/flytectl/releases/download/v0.6.30/flytectl_Darwin_x86_64.tar.gz"
      sha256 "861f60132e996155996e35f8c59f97cd63c83a51c92a25fb58b8b725c3a9c771"

      def install
        bin.install "flytectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flyteorg/flytectl/releases/download/v0.6.30/flytectl_Linux_x86_64.tar.gz"
      sha256 "2c49cec58b2e5e6cb11809755bbab736ebba81bc8a75280405e69a9d8f9808b2"

      def install
        bin.install "flytectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyteorg/flytectl/releases/download/v0.6.30/flytectl_Linux_arm64.tar.gz"
      sha256 "10dba3bbeb64098e849f207edb80c300bd58f3a9fae920c3ca7054149165ca4e"

      def install
        bin.install "flytectl"
      end
    end
  end
end
